config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  post '/resume' => 'welcome#resume'
  get '/resume' => 'welcome#resume'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def resume
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ben Doane
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    %nav.navbar.navbar-custom.navbar-fixed-top
      .container
        .navbar-header
          .navbar-brand
            .dark-logo{:width => "95"}
              = link_to "Ben Doane", root_url
          %button.navbar-toggle{"data-target" => "#custom-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #custom-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a{"data-toggle" => "dropdown", :href => ""} Portfolio
              %ul.dropdown-menu{:role => "menu"}
                %li.dropdown
                  = link_to "All the Swing Dancing", "http://www.alltheswingdancing.com"
                %li.dropdown
                  = link_to "Todoodles", "https://salty-journey-3187.herokuapp.com/"
                %li.dropdown
                  = link_to "Github", "https://github.com/bendoane"
            -# %li.dropdown
            -#   %a{"data-toggle" => "dropdown", :href => ""} Blog
            -#   %ul.dropdown-menu{:role => "menu"}
            -#     %li.dropdown
            -#       = link_to "Building Code", "http://uptobuildingcode.blogspot.com/"
            %li.dropdown
              = link_to "Resume", resume_path
            %li.dropdown
              %a{"data-toggle" => "dropdown", :href => ""} Contact
              %ul.dropdown-menu{:role => "menu"}
                %li.dropdown
                  %a{"data-toggle" => "dropdown", :href => "mailto:ben.doane@gamil.com"} ben.doane@gmail.com
                  -# NOTE have a page made for emailing to me
                %li.dropdown
                  %a{"data-toggle" => "dropdown"} Ph. 812-499-1621
                %li.dropdown
                  = link_to "Linked In", "https://www.linkedin.com/in/ben-doane-b9040348"
    = yield

app/views/welcome/index.html.haml
.wrapper
  %section#hero.module-hero.module-parallax.bg-light-60
    .hero-caption
      .hero-text
        %h1.mh-line-size-2.font-alt.m-b-50 Benjamin Doane
        %br/
        %h5.mh-line-size-5.font-alt.m-b-50 Software Developer
  %hr.divider/
  %section.module
    .container
      .row
        .col-sm-6.col-sm-offset-3
          %h2.module-title.font-alt About Ben Doane
          .module-subtitle.font-serif
            Software Developer. Extrovert. Dance Teacher. Dark Beer Drinker.
      .row
        .col-sm-6
          %h5.font-alt.m-t-0.m-b-20 I'm a creative thinker
          My undergraduate degree is in Landscape Architecture.
          %br
          I went back school for
          software development.
          %br
          I'm driven by my creativity and my desire to solve problems.
          %br
          After my 5 year degree in Architecture, I found my calling in building code.
          %br
          (Just a
          different kind)
          %br
          I'm amazed by the similarities the two share in their problem
          solving nature.
          %br
          In my journey as a developer, I’ve discovered my
          passion for learning, growing, and problem solving.
        %br/

        .col-sm-6
          %h6.progress-title.font-alt Back-End - Ruby on Rails
          .progress
            .progress-bar.pb-dark{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "65", :role => "progressbar", :style => "width: 80%;"}
              %span.font-alt{:style => "opacity: 1;"}
          %h6.progress-title.font-alt Front-End - HTML, CSS, JavaScript
          .progress
            .progress-bar.pb-dark{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 50%;"}
              %span.font-alt{:style => "opacity: 1;"}
          %h6.progress-title.font-alt Communication &amp; Public Speaking
          .progress
            .progress-bar.pb-dark{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "85", :role => "progressbar", :style => "width: 95%;"}
              %span.font-alt{:style => "opacity: 1;"}
          %h6.progress-title.font-alt Design & Problem Solving
          .progress
            .progress-bar.pb-dark{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "75", :role => "progressbar", :style => "width: 75%;"}
              %span.font-alt{:style => "opacity: 1;"}
          %br/
          %br
        %h2.module-subtitle.font-alt Love what you do || Have fun doing it
  %hr.divider/

-# NOTE This needs a ton of redoing.
  -# %section#services.module
  -#   .container
  -#     .row
  -#       .col-sm-6.col-sm-offset-3
  -#         %h2.module-title.font-alt Stack
      -# .row
      -#   .col-xs-4
      -#     .content-box
      -#       .content-box-icon{:style => "padding-top:70px;"}
      -#         = image_tag('Javascript.png')
      -#       %h5.content-box-title.font-alt JavaScript
      -#   .col-xs-4
      -#     .content-box
      -#       .content-box-icon
      -#         = image_tag("ruby-on-rails.png")
      -#       %h5.content-box-title.font-alt Ruby on Rails
      -#       .content-box-text
      -#   .col-xs-4
      -#     .content-box
      -#       .content-box-icon{:style => "padding-top:70px;"}
      -#         = image_tag("html-icon.png")
      -#       %h5.content-box-title.font-alt HTML, CSS, &amp; Bootstrap
      -#
      -# .row
      -#   -# .col-xs-4
      -#   -#   .content-box
      -#   -#     .content-box-icon
      -#   -#       = image_tag("api-icon.png")
      -#   -#     %h5.content-box-title.font-alt RESTful APIs
      -#   .col-xs-4
      -#     .content-box
      -#       .content-box-icon
      -#         = image_tag("Github-icon.png")
      -#       %h5.content-box-title.font-alt Git-flow &amp; Github
      -#   .col-xs-4
      -#     .content-box
      -#       .content-box-icon
      -#         = image_tag("heroku-icon.png")
      -#       %h5.content-box-title.font-alt Heroku

%hr.divider/

.container
  .row
    .col-sm-6.col-sm-offset-3
      %h2.module-title.font-alt Portfolio of Works
      .module-subtitle.font-serif
        \~~ Other than this webpage itself ~~

  .row
    .works-grid-wrapper
      .works-grid.works-hover-w
        .col-xs-4.img-responsive
          .work-item.design{:style => "height: 325px;"}
            %a{:href => "https://salty-journey-3187.herokuapp.com/"}
              = image_tag("Todoodles-icon.png")
              .work-caption.font-alt
                %h3.work-title Todoodles
                .work-descr
                  A Simple List &amp; Task Managing App
        .col-xs-4.img-responsive
          .work-item.design{:style => "height: 325px;;"}
            %a{:href => "http://www.alltheswingdancing.com"}
              = image_tag("alltheswingdancing2x500.png")
              .work-caption.font-alt
                %h3.work-title All the Swing Dancing
                .work-descr
                  Swing Dance Event Posting and Tacking Site
        .col-xs-4.img-responsive
          .work-item.design{:style => "height: 325px;"}
            %a{:href => "https://arcane-shore-9616.herokuapp.com/"}
              = image_tag("globe-icon.png")
              .work-caption.font-alt
                %h3.work-title Indy Rubyists
                .work-descr
                  Find a Rubyist in Indy via GitHub API

  %br/

  .row.m-t-70.text-center
    .col-sm-12
      = link_to "More on Github", "https://github.com/bendoane", class: "btn btn-round btn-b"

%br/

%hr.divider/

%br/
%br/
%hr.divider/

%section#footer.module-small.bg-light
  .container
    .row.m-t-40
      .col-sm-1
      .col-sm-3
        %h5.font-alt.m-t-0.m-b-20 TL;DR
        Extrovert
        %br
        Designer
        %br
        Web Developer
        %br
        You should work with him.
      .col-sm-3
        %h5.font-alt.m-t-0.m-b-20 Follow
        %ul.list-unstyled
          %li
            %a{:href => "https://www.linkedin.com/in/ben-doane-b9040348"} Linked In
          %li
            %a{:href => "https://github.com/bendoane"} Github
          -# %li
          -#   %a{:href => "http://uptobuildingcode.blogspot.com/"} Blogger
      .col-sm-2
        %h5.font-alt.m-t-0.m-b-20 Connect
        ben.doane@gmail.com
        %br/
        Tel: 1-812-499-1621
        %hr/
        = button_to "I'm Ron Burgundy?", resume_path, class:"btn btn-round btn-b"
      .col-sm-3.img-responsive
        = image_tag("ben-ron-burgundy.png")
%hr.divider/
%footer
  .container
    .col-sm-12
      %p.copyright.text-center.m-b-0 © 2017 Ben Doane, All Rights Reserved.

app/views/welcome/resume.html.erb
<div class="wrapper">

<div class="container">
  <div class="resume">
    <%=image_tag("BenDoaneResume.jpg")%>
  </div>
  <br>
  <div class="row m-t-70 text-center">
    <div class="col-sm-12">
      <%=link_to "Back", root_url, class: "btn btn-round btn-b"%>
    </div>
  </div>
  <br>
</div>


</div>